service: nestjs-lambda

provider:
  name: aws
  runtime: nodejs14.x

functions:
  app:
    handler: dist/src/main.handler
    timeout: 30
    events:
      - http:
          path: /
          method: any
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline

custom:
  serverless-offline:
    port: 3000
    babelOptions:
      presets: ["env"]
